//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int messageid { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string message { get; set; }
    }
}
