//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class faultdetail
    {
        public int faultid { get; set; }
        public int processid { get; set; }
        public string issue { get; set; }
        public string description { get; set; }
        public decimal initialprice { get; set; }
        public decimal finalprice { get; set; }
        public string actions { get; set; }
    }
}
