//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicedetail
    {
        public int invoicedetailid { get; set; }
        public string product { get; set; }
        public short quantity { get; set; }
        public decimal price { get; set; }
        public decimal total { get; set; }
        public int invoiceid { get; set; }
    
        public virtual invoiceinfo invoiceinfo { get; set; }
    }
}
