//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoiceinfo()
        {
            this.invoicedetail = new HashSet<invoicedetail>();
        }
    
        public int invoiceid { get; set; }
        public string series { get; set; }
        public string serialno { get; set; }
        public System.DateTime invoicedate { get; set; }
        public string invoicetime { get; set; }
        public string taxoffice { get; set; }
        public int customerid { get; set; }
        public int staffid { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicedetail> invoicedetail { get; set; }
        public virtual staff staff { get; set; }
    }
}
