//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttracking
    {
        public int trackingid { get; set; }
        public string status { get; set; }
        public System.DateTime trackingdate { get; set; }
        public string serialno { get; set; }
        public string comment { get; set; }
    }
}
