//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class productmovement
    {
        public int movementid { get; set; }
        public int productid { get; set; }
        public int customerid { get; set; }
        public int staffid { get; set; }
        public System.DateTime movementdate { get; set; }
        public short quantity { get; set; }
        public decimal price { get; set; }
        public string productserialno { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
        public virtual staff staff { get; set; }
        public virtual product product1 { get; set; }
    }
}
